import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ToastsContainer } from '@/shared/ui/feedback/toast/toasts-container';
import './globals.css';

const inter = Inter({
  subsets: ['latin', 'cyrillic'],
  variable: '--font-inter',
  weight: ['400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang='en' className={`${inter.variable} h-full antialiased`}>
      <body className='min-h-full flex flex-col justify-center items-center base-100'>
        {children}
        <ToastsContainer />
      </body>
    </html>
  );
}
